### PR TITLE
Refactored and added dequeueAppend

### PR DESCRIPTION
**Pull request by moredure**
DequeueAppend allows to dequeue data without allocations at all by reusing byte slice
Increased speed of Dequeue/Enqueue methods by omitting interfaces usage, some code duplications possible, but it's a Golang before generics)

### CODE REVIEW

**Comment by moredure** [comment]
As a conter measure for code duplications we can use unsafe package to convert bytes to strings and strings to bytes, @mangalaman93 what do you think?

**Comment by moredure** [comment]
I used unsafe since mmap already using unsafe

**Comment by mangalaman93** [comment]
Thanks for the PR @moredure. These are my initial thoughts, give me some time to think about these more.

I like the idea that Dequeue should be able to copy the data into a provided byte slice but I don't think I like the idea of having two separate Dequeue function. I think it should be straight forward to merge the two into one function.

I also don't like the idea of using unsafe, let me see if we could live without using unsafe and still have optimal code.

Additionally, I have been thinking and I think we should have `Peek` function too in the API given that the bigqueue is persistent and if you remove something, you can't put it back.

**Comment by moredure** [comment]
@mangalaman93 I removed unsafe usage and returned some redundant strings functions

**Pull request closed without merging**
